language: cpp
os:
 - linux
 - osx
compiler:
  - gcc
matrix:
  allow_failures:
    - os: osx
env:
 - CMAKE_DIR="v3.0" CMAKE_VERSION="3.0.1"
 - CMAKE_DIR="v2.8" CMAKE_VERSION="2.8.12.2"
notifications:
  slack: fallto:MlnVOMNkx8YopsaSSxqh2Rcr
before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install mercurial
  - sudo apt-get install git  
  - sudo apt-get install subversion
  - git config --global user.email "travis-ci@example.com"
  - git config --global user.name "Build Server"
install:
  - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
  - bii setup:cpp
  - bii init
  - bii open toeb/cmakepp
  - rsync -av --exclude="blocks" --exclude="bii" --exclude=".git" --exclude=".gitignore" . blocks/toeb/cmakepp > /dev/null
  #- sudo apt-get install cmake
  #- cmake --version
  # install cmake --
  - wget "http://www.cmake.org/files/${CMAKE_DIR}/cmake-${CMAKE_VERSION}.tar.gz"
  - tar xf "cmake-${CMAKE_VERSION}.tar.gz"
  - cmake -Hcmake-${CMAKE_VERSION} -B_builds -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="`pwd`/_install"
  - cmake --build _builds --target install
  - export PATH="`pwd`/_install/bin:${PATH}"
  # -- end
  # verify installed cmake --
  - which cmake
  - cmake --version    
  #-- end
 
script: 
 - cmake -P build/script.cmake

after_success: "cmake -P build/after_success.cmake"
after_failure: "cmake -P build/after_failure.cmake"
after_script: "cmake -P build/after_script.cmake"

deploy:
  - provider: biicode
    user: toeb
    password: 
     secure: "FbBmlMqDcpJ0rJ12I/H8CWwPnVe44zsGuL+5h+16JjZBQU8+TUizaw/Wns3OnQXzvvdeyzUvypGrnq0g7t+MFareWZ+rYVHRNibjsx5OxubvcgM6+fbXAu8G2f4bXHZPun5IMf8+1OCg8ETEQ/kEHtDDVOFO24Gb49N9Td3chgQ="
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
  - provider: releases
    api_key:
      secure: Y8fO6kLjCkPHi7qa1tkv9kVKvoEe/VsRO9gY8LFFsBliKFD1DC/+Sf1l5ij3SGawFduzCWWk4O62lEVawEnUhOqHFb+D6+SExVzF5QvkgSvnp6BkpyosvCn0/FXBy4tt4KZyLSJ3CzqLvDnD99d7vouHyxiLZy4JSTjmlnklkAo=
    file: release/cmakepp.cmake
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
