language: cpp
compiler:
  - gcc
notifications:
  slack: fallto:MlnVOMNkx8YopsaSSxqh2Rcr
before_install:
  - sudo apt-get install cmake
  - sudo apt-get install mercurial
  - git config --global user.email "travis-ci@example.com"
  - git config --global user.name "Build Server"
script: "cmake -P oo-cmake-tests.cmake"
branches:
  only:
    - master
    - devel
